  removeAllWeapons player;
  player addWeapon 'BAF_AS50_TWS'; 
  player addMagazine '5Rnd_127x99_as50'; 
  player addMagazine '5Rnd_127x99_as50'; 
  player addMagazine '5Rnd_127x99_as50'; 
  player addMagazine '5Rnd_127x99_as50'; 
  player addMagazine '5Rnd_127x99_as50'; 
  player addMagazine '5Rnd_127x99_as50'; 
  player addMagazine '5Rnd_127x99_as50'; 
  player addMagazine 'ItemPainkiller'; 
  player addMagazine 'ItemPainkiller'; 
  player addMagazine 'ItemMorphine'; 
  player addMagazine 'ItemMorphine'; 
  player addMagazine 'Skin_Sniper1_DZ'; 

  player addWeapon 'UZI_SD_EP1';
  player addMagazine '30Rnd_9x19_UZI_SD'; 
  player addMagazine '30Rnd_9x19_UZI_SD'; 
  player addMagazine '30Rnd_9x19_UZI_SD'; 
  player addMagazine '30Rnd_9x19_UZI_SD'; 
  player addMagazine '30Rnd_9x19_UZI_SD'; 
  player addMagazine 'ItemBandage'; 
  player addMagazine 'ItemBandage'; 
  player addMagazine 'ItemBandage';

  player addWeapon 'Binocular_Vector';
  player addWeapon 'NVGoggles';
  player addWeapon 'ItemGPS';
  player addWeapon 'ItemRadio';
  player addWeapon 'ItemFlashlightRed';
  player addWeapon 'ItemCompass';
  player addWeapon 'ItemMap';
  player addWeapon 'ItemWatch';
  player addWeapon 'ItemHatchet';
  player addWeapon 'ItemKnife';
  player addWeapon 'Itemmatchbox';
  player addWeapon 'Itemetool';
  player addWeapon 'Itemtoolbox';
  player addBackpack 'DZ_Backpack_EP1';
  (Unitbackpack player) addWeaponCargo ['M4A1_HWS_GL_SD_Camo', 1];
  (Unitbackpack player) addMagazineCargo ['30Rnd_556x45_StanagSD', 6];
  (Unitbackpack player) addMagazineCargo ['ItemBloodbag', 2];
  (Unitbackpack player) addMagazineCargo ['ItemEpinephrine', 1];
  (Unitbackpack player) addMagazineCargo ['ItemWaterbottle', 2];
  (Unitbackpack player) addMagazineCargo ['FoodSteakCooked', 3];