GearAdd = (vehicle player);
GearAdd addWeapon 'ItemHatchet';
GearAdd addWeapon 'ItemKnife';
GearAdd addWeapon 'Itemmatchbox';
GearAdd addWeapon 'Itemetool';
GearAdd addWeapon 'Itemtoolbox';
GearAdd addBackpack 'DZ_Backpack_EP1';
(Unitbackpack GearAdd) addMagazineCargoGlobal ['workbench_kit', 2];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['wood_shack_kit', 2];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['deer_stand_kit', 2];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['wooden_shed_kit', 2];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['storage_shed_kit', 2];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['outhouse_kit', 1];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['forest_net_kit', 2];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['forest_large_net_kit', 2];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemTentDomed2', 2];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['light_pole_kit', 6];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemWoodWallLg', 10];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemWoodFloor', 10];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemFuelPump', 2];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemGenerator', 2];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['sandbag_nest_kit', 2];
